# Generated by Django 3.1.4 on 2020-12-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_auto_20201204_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(default='', max_length=40)),
                ('phone', models.CharField(default='', max_length=30)),
                ('msg', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
