# Generated by Django 3.1.4 on 2020-12-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.CharField(default='', max_length=40)),
                ('pwd1', models.CharField(default='', max_length=30)),
                ('pwd2', models.CharField(default='', max_length=30)),
            ],
        ),
    ]
