# Generated by Django 3.1.4 on 2020-12-10 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0004_createuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CreateUser',
        ),
    ]
